import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useState, useRef } from 'react'

type LoginState = {
  login?: boolean
  code?: number
  message?: string
}

const initialLoginState: LoginState = {
  login: false
}

const Home: NextPage = () => {
  const [loginState, setLoginState] = useState<LoginState>(initialLoginState)
  const idRef = useRef<HTMLInputElement>(null)
  const passRef = useRef<HTMLInputElement>(null)

  const handleLogin = () => {
    if (!idRef.current || !passRef.current) {
      return
    }
    fetch("https://127.0.0.1:4000/api/login", {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Content-Type': 'application/json'
      },
      credentials: 'include',
      body: JSON.stringify({
        id: idRef.current.value,
        pass: passRef.current.value,
      })
    }).then( res => res.json() )
      .then( res => {
        setLoginState(res);
      })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          {!loginState.login
            ? <div>
                <div>ID: <input ref={idRef} name="id" type="text" /></div>
                <div>Pass: <input ref={passRef} name="pass" type="password" /></div>
                <button onClick={handleLogin}>ログイン</button>
                <div>{JSON.stringify(loginState)}</div>
              </div>
            : <div>
                <div>ログイン済</div>
                <div>{JSON.stringify(loginState)}</div>
              </div>}
        </div>
      </main>
    </div>
  )
}

export default Home
